# Generated by Django 5.1.6 on 2025-02-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lanches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
