# Generated by Django 5.1.6 on 2025-02-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lanches', '0003_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
