# Generated by Django 5.1.6 on 2025-02-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lanches', '0005_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
